spring: 
  profiles: default
  influxdb: 
    connect-timeout: 1000
    database: boot
    gzip: true
    password: secret
    read-timeout: 10
    retention-policy: autogen
    url: http://localhost:8086
    username: admin
    write-timeout: 10
    
management:
  metrics:
    export:
      influx:
        db: boot
        uri: http://10.1.20.25:8086
        auto-create-db: false